import Head from 'next/head'
import Image from 'next/image'
import { Layout } from 'antd'
import styles from '../styles/Home.module.css'

const { Header, Content, Footer } = Layout;

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <div className={styles.logo} />
      </Header>

      <Content className={styles.content}><h1>Test</h1></Content>

      <Footer className={styles.footer}>
        URL Shortener
      </Footer>
    </Layout>
  )
}
